name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: '[BUG]: '
labels: ['bug', 'triage']
assignees: ['Ghenghis']

body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight Checklist
      description: Please ensure you've completed all of the following
      options:
        - label: I have searched the existing issues to make sure this bug has not been reported
          required: true
        - label: I am using the latest version of the configuration
          required: true
        - label: I have read the documentation
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Bug Category
      description: What category does this bug fall into?
      options:
        - Editor Performance
        - File System Operations
        - Language Server
        - AI/Cascade Features
        - Extension Integration
        - Security
        - Configuration
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Open Windsurf IDE
        2. Navigate to...
        3. Perform action...
        4. Observe error
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      value: |
        - **OS**: Windows 11
        - **Windsurf Version**: 
        - **Node.js Version**: 
        - **Python Version**: 
        - **PowerShell Version**:
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please paste any relevant log output
      render: shell

  - type: textarea
    id: settings
    attributes:
      label: Relevant Settings
      description: If applicable, paste relevant settings.json excerpt
      render: json

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical - Blocks all work
        - High - Major feature broken
        - Medium - Feature impaired
        - Low - Minor inconvenience
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information
