name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: '[FEATURE]: '
labels: ['enhancement', 'triage']
assignees: ['Ghenghis']

body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Thanks for suggesting a new feature! Please describe your idea in detail.

  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight Checklist
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: I have read the project documentation
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature fall into?
      options:
        - Editor Configuration
        - Performance Optimization
        - Language Support
        - AI/Cascade Features
        - Extension Integration
        - Security Enhancement
        - Developer Experience
        - Documentation
        - Testing/Validation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: A clear description of the problem or limitation you're experiencing...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution
      placeholder: A clear description of what you want to happen...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you've considered?
      placeholder: Describe any alternative solutions or workarounds...

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Details
      description: If you have ideas on how to implement this, please share
      placeholder: Technical details, code samples, configuration examples...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my workflow
        - High - Would significantly improve my experience
        - Medium - Nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help implement this feature?
      options:
        - label: I am willing to submit a PR for this feature
        - label: I can help test this feature
        - label: I can help document this feature
